INSERT INTO FARMACO.ROL (ID_ROL, NAME, DESCRIPTION, CREATED_AT, STATUS)
SELECT 1, 'ADMIN', 'Rol de administrador', SYSTIMESTAMP, 'A' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM FARMACO.ROL WHERE UPPER(NAME) = 'ADMIN');


INSERT INTO FARMACO.ROL (ID_ROL, NAME, DESCRIPTION, CREATED_AT, STATUS)
SELECT 2, 'MEDICO', 'Rol de médico', SYSTIMESTAMP, 'A' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM FARMACO.ROL WHERE UPPER(NAME) = 'MEDICO');

INSERT INTO FARMACO.ROL (ID_ROL, NAME, DESCRIPTION, CREATED_AT, STATUS)
SELECT 3, 'FARMACOLOGO', 'Rol de farmacólogo', SYSTIMESTAMP, 'A' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM FARMACO.ROL WHERE UPPER(NAME) = 'FARMACOLOGO');
