DROP TABLE FARMACO.USUARIO;
DROP TABLE FARMACO.ROL;
DROP TABLE FARMACO.USER_ROL;
DROP TABLE FARMACO.PACIENTE;
DROP TABLE FARMACO.MEDICAMENTO;
DROP TABLE FARMACO.RECETA;
DROP TABLE FARMACO.DETALLE_RECETA;
DROP TABLE FARMACO.HISTORIAL_MEDICO;
DROP TABLE FARMACO.EFECTO_ADVERSO 

FARMACO.PACIENTE
FARMACO.MEDICAMENTO
FARMACO.RECETA
FARMACO.DETALLE_RECETA
FARMACO.HISTORIAL_MEDICO
FARMACO.EFECTO_ADVERSO




CREATE TABLE FARMACO.USUARIO (
  ID_USER   NUMBER NOT NULL,
  USERNAME     VARCHAR2(50)  NOT NULL,
  NAME       VARCHAR2(100) NOT NULL,
  LASTNAME     VARCHAR2(100) NOT NULL,
  EMAIL        VARCHAR2(120),
  PASSWORD    VARCHAR2(255) NOT NULL,
  STATUS VARCHAR2(1), -- A: Activo, I: Inactivo
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    -- Fecha de creación
  UPDATED_AT TIMESTAMP  
  );

ALTER TABLE FARMACO.USUARIO 
  ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USER);
ALTER TABLE FARMACO.USUARIO
  ADD CONSTRAINT UQ_USUARIO_USERNAME UNIQUE (USERNAME);
ALTER TABLE FARMACO.USUARIO
  ADD CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL);

/* ===================== USUARIO_ROL ===================== */
CREATE TABLE FARMACO.USER_ROL (
    ID_USER NUMBER NOT NULL,                           -- ID del usuario
    ID_ROL NUMBER NOT NULL,                           -- ID del rol
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP   -- Fecha de asignación
);

ALTER TABLE FARMACO.USER_ROL
  ADD CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (ID_USER, ID_ROL);
ALTER TABLE FARMACO.USER_ROL
  ADD CONSTRAINT FK_UR_USUARIO FOREIGN KEY (ID_USER) REFERENCES FARMACO.USUARIO(ID_USER);
ALTER TABLE FARMACO.USER_ROL
  ADD CONSTRAINT FK_UR_ROL FOREIGN KEY (ID_ROL) REFERENCES FARMACO.ROL(ID_ROL);

/* ===================== ROL ===================== */
CREATE TABLE FARMACO.ROL (
    ID_ROL NUMBER NOT NULL, -- ID único auto-incremental
    NAME VARCHAR2(50) NOT NULL,                 -- Nombre del rol (Admin, User, etc.)
    DESCRIPTION VARCHAR2(255),                         -- Descripción del rol
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    -- Fecha de creación
    STATUS VARCHAR2(1) -- A: Activo, I: Inactivo
);

ALTER TABLE FARMACO.ROL ADD CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL);

ALTER TABLE FARMACO.ROL
  ADD CONSTRAINT UQ_ROL_NAME UNIQUE (NAME);

/* ===================== PACIENTE ===================== */
CREATE TABLE FARMACO.PACIENTE (
    ID_PACIENTE      NUMBER(19),
    NOMBRE           VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE          NOT NULL,
    GENERO           CHAR(1)       NOT NULL,
    CONTACTO         VARCHAR2(100) NOT NULL,
    FECHA_REGISTRO   DATE          NOT NULL
);

ALTER TABLE FARMACO.PACIENTE
  ADD CONSTRAINT PK_PACIENTE PRIMARY KEY (ID_PACIENTE);

/* ===================== MEDICAMENTO ===================== */
CREATE TABLE FARMACO.MEDICAMENTO (
    ID_MEDICAMENTO     NUMBER(10) ,
    NOMBRE             VARCHAR2(100) NOT NULL,
    COMPOSICION        CLOB          NOT NULL,
    INDICACIONES       CLOB          NOT NULL,
    CONTRAINDICACIONES CLOB          NOT NULL,
    FECHA_REGISTRO     DATE          NOT NULL
);

ALTER TABLE FARMACO.MEDICAMENTO
  ADD CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO);

/* ===================== RECETA ===================== */
CREATE TABLE FARMACO.RECETA (
    ID_RECETA     NUMBER(10) ,
    ID_PACIENTE   NUMBER(19),
    ID_MEDICO     NUMBER(19),
    FECHA_EMISION DATE NOT NULL,
    OBSERVACIONES CLOB
);

ALTER TABLE FARMACO.RECETA
  ADD CONSTRAINT PK_RECETA PRIMARY KEY (ID_RECETA);

ALTER TABLE FARMACO.RECETA
  ADD CONSTRAINT FK_RECETA_PACIENTE
    FOREIGN KEY (ID_PACIENTE)
    REFERENCES FARMACO.PACIENTE (ID_PACIENTE);

ALTER TABLE FARMACO.RECETA
  ADD CONSTRAINT FK_RECETA_USUARIO_MEDICO
  FOREIGN KEY (ID_MEDICO)
  REFERENCES FARMACO.USUARIO(ID_USER);

/* ===================== DETALLE_RECETA ===================== */
CREATE TABLE FARMACO.DETALLE_RECETA (
    ID_DETALLE     NUMBER(10),
    ID_RECETA      NUMBER(10),
    ID_MEDICAMENTO NUMBER(10),
    DOSIS          VARCHAR2(50) NOT NULL,
    FRECUENCIA     VARCHAR2(50) NOT NULL,
    DURACION       VARCHAR2(50) NOT NULL
);

ALTER TABLE FARMACO.DETALLE_RECETA
  ADD CONSTRAINT PK_DETALLE_RECETA PRIMARY KEY (ID_DETALLE);

ALTER TABLE FARMACO.DETALLE_RECETA
  ADD CONSTRAINT FK_DETREC_RECETA
    FOREIGN KEY (ID_RECETA)
    REFERENCES FARMACO.RECETA (ID_RECETA);

ALTER TABLE FARMACO.DETALLE_RECETA
  ADD CONSTRAINT FK_DETREC_MEDICAMENTO
    FOREIGN KEY (ID_MEDICAMENTO)
    REFERENCES FARMACO.MEDICAMENTO (ID_MEDICAMENTO);

/* ===================== HISTORIAL_MEDICO ===================== */
CREATE TABLE FARMACO.HISTORIAL_MEDICO (
    ID_HISTORIAL NUMBER(10) ,
    ID_PACIENTE  NUMBER(19),
    ID_MEDICO    NUMBER(19),
    FECHA        DATE NOT NULL,
    DIAGNOSTICO  CLOB NOT NULL,
    TRATAMIENTO  CLOB NOT NULL
);

ALTER TABLE FARMACO.HISTORIAL_MEDICO
  ADD CONSTRAINT PK_HISTORIAL_MEDICO PRIMARY KEY (ID_HISTORIAL);

ALTER TABLE FARMACO.HISTORIAL_MEDICO
  ADD CONSTRAINT FK_HISTMED_PACIENTE
    FOREIGN KEY (ID_PACIENTE)
    REFERENCES FARMACO.PACIENTE (ID_PACIENTE);

ALTER TABLE FARMACO.HISTORIAL_MEDICO
  ADD CONSTRAINT FK_HISTMED_USUARIO_MEDICO
  FOREIGN KEY (ID_MEDICO)
  REFERENCES FARMACO.USUARIO(ID_USER);

/* ===================== EFECTO_ADVERSO ===================== */
CREATE TABLE FARMACO.EFECTO_ADVERSO (
    ID_EFECTO           NUMBER(10) ,
    ID_PACIENTE         NUMBER(19),
    ID_MEDICAMENTO      NUMBER(10),
    FECHA_REPORTE       DATE NOT NULL,
    DESCRIPCION         CLOB NOT NULL,
    GRAVEDAD            VARCHAR2(50) NOT NULL,
    LOTE                VARCHAR2(50) NOT NULL,
    LABORATORIO         VARCHAR2(100) NOT NULL,
    REGISTRO_SANITARIO  VARCHAR2(50) NOT NULL,
    FECHA_VENCIMIENTO   DATE NOT NULL,
    DOSIS               VARCHAR2(50),
    FECHA_INICIO_EFECTO DATE,
    FECHA_FIN_EFECTO    DATE,
    VIA_ADMINISTRACION  VARCHAR2(50),
    MEDIDAS_TOMADAS     CLOB,
    SUSPENSION          CHAR(1),
    FECHA_SUSPENSION    DATE,
    AJUSTE_DOSIS        CHAR(1),
    DOSIS_ACTUAL        VARCHAR2(50)
);

ALTER TABLE FARMACO.EFECTO_ADVERSO
  ADD CONSTRAINT PK_EFECTO_ADVERSO PRIMARY KEY (ID_EFECTO);

ALTER TABLE FARMACO.EFECTO_ADVERSO
  ADD CONSTRAINT FK_EFADV_PACIENTE
    FOREIGN KEY (ID_PACIENTE)
    REFERENCES FARMACO.PACIENTE (ID_PACIENTE);

ALTER TABLE FARMACO.EFECTO_ADVERSO
  ADD CONSTRAINT FK_EFADV_MEDICAMENTO
    FOREIGN KEY (ID_MEDICAMENTO)
    REFERENCES FARMACO.MEDICAMENTO (ID_MEDICAMENTO);



