CREATE OR REPLACE TRIGGER FARMACO.TRG_RECETA_CHECK_MEDICO
BEFORE INSERT OR UPDATE OF ID_MEDICO ON FARMACO.RECETA
FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  IF :NEW.ID_MEDICO IS NOT NULL THEN
    SELECT COUNT(*)
      INTO v_count
      FROM FARMACO.USER_ROL ur
      JOIN FARMACO.ROL r ON r.ID_ROL = ur.ID_ROL
     WHERE ur.ID_USER = :NEW.ID_MEDICO
       AND UPPER(r.NAME) = 'MEDICO';

    IF v_count = 0 THEN
      RAISE_APPLICATION_ERROR(-20001, 'El usuario no tiene el rol MEDICO.');
    END IF;
  END IF;
END;

CREATE OR REPLACE TRIGGER FARMACO.TRG_HMED_CHECK_MEDICO
BEFORE INSERT OR UPDATE OF ID_MEDICO ON FARMACO.HISTORIAL_MEDICO
FOR EACH ROW
DECLARE
  v_count NUMBER;
BEGIN
  IF :NEW.ID_MEDICO IS NOT NULL THEN
    SELECT COUNT(*)
      INTO v_count
      FROM FARMACO.USER_ROL ur
      JOIN FARMACO.ROL r ON r.ID_ROL = ur.ID_ROL
     WHERE ur.ID_USER = :NEW.ID_MEDICO
       AND UPPER(r.NAME) = 'MEDICO';

    IF v_count = 0 THEN
      RAISE_APPLICATION_ERROR(-20002, 'El usuario no tiene el rol MEDICO.');
    END IF;
  END IF;
END;