ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER FARMACO IDENTIFIED BY fARMACO123;
GRANT CREATE SESSION, RESOURCE TO FARMACO;
GRANT CREATE JOB TO FARMACO;
REVOKE CREATE JOB FROM FARMACO;

CREATE USER OP_FARMACO IDENTIFIED BY OP_FARMACO123;
GRANT CREATE SESSION TO OP_FARMACO;
GRANT CONNECT TO OP_FARMACO;

CREATE USER USR_CONSULTA_FARMACO IDENTIFIED BY USR_CONSULTA_FARMACO123;
GRANT CREATE SESSION TO USR_CONSULTA_FARMACO;
GRANT CONNECT TO USR_CONSULTA_FARMACO;

CREATE USER LALMAZAN IDENTIFIED BY "Luis1234";
GRANT CREATE SESSION TO LALMAZAN;
GRANT CONNECT TO LALMAZAN;
GRANT DBA TO LALMAZAN;

ALTER USER FARMACO QUOTA UNLIMITED ON USERS;
ALTER USER OP_FARMACO QUOTA UNLIMITED ON USERS;
ALTER USER USR_CONSULTA_FARMACO QUOTA UNLIMITED ON USERS;


CREATE ROLE SELECT_FARMACO; 

CREATE ROLE OPERACIONES_FARMACO; 


GRANT SELECT_FARMACO TO USR_CONSULTA_FARMACO;
GRANT OPERACIONES_FARMACO TO OP_FARMACO;


CREATE OR REPLACE TRIGGER FARMACO.TRG_GRANT_SELECT
AFTER CREATE ON SCHEMA
DECLARE
  job_name  VARCHAR2(128);
BEGIN
  IF ora_dict_obj_type = 'TABLE' THEN
    job_name := 'J_GRANT_'||ora_dict_obj_name||'_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');

    DBMS_SCHEDULER.create_job(
      job_name   => job_name,
      job_type   => 'PLSQL_BLOCK',
      job_action => 'BEGIN '||
                    '  EXECUTE IMMEDIATE ''GRANT SELECT ON FARMACO.'||ora_dict_obj_name||' TO SELECT_FARMACO'';'||
                    'END;',
      start_date => SYSTIMESTAMP + INTERVAL '5' SECOND,  -- corre fuera del DDL
      enabled    => TRUE,
      auto_drop  => TRUE
    );
  END IF;
END;

-- Trigger para otorgar permisos automáticamente al crear tablas
CREATE OR REPLACE TRIGGER FARMACO.TRG_GRANT_OPERACIONES
AFTER CREATE ON SCHEMA
DECLARE
  job_name  VARCHAR2(128);
BEGIN
  IF ora_dict_obj_type = 'TABLE' THEN
    job_name := 'J_GRANT_'||ora_dict_obj_name||'_'||TO_CHAR(SYSTIMESTAMP,'YYYYMMDDHH24MISSFF3');

    DBMS_SCHEDULER.create_job(
      job_name   => job_name,
      job_type   => 'PLSQL_BLOCK',
      job_action => 'BEGIN '||
                    '  EXECUTE IMMEDIATE ''GRANT SELECT, INSERT, UPDATE, DELETE ON FARMACO.'||ora_dict_obj_name||' TO OPERACIONES_FARMACO'';'||
                    'END;',
      start_date => SYSTIMESTAMP + INTERVAL '5' SECOND,  -- corre fuera del DDL
      enabled    => TRUE,
      auto_drop  => TRUE
    );
  END IF;
END;
